### ISSUE TITLE
Need to replace SMILES from rcellminer to DrugCell

### ISSUE THREAD

**Issue by inoue0426** [cannin/graph_neural_network_drug_response#11]
[b69f9e5](https://github.com/cannin/graph_neural_network_drug_response/commit/b69f9e5467e1bc9027d7cb542b96281189a39d9e)

Cannot use SMILES from rcellminer directory because DrugCell created pretrained model using SMILES from GDSC or CTRP and this is not the same with rcellminer's SMILES.

```python

python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/drugcell_v1.pt \
            -predict data/rcellminer_test.txt

Traceback (most recent call last):
  File "/Users/yoshitakainoue/code/graph_neural_network_drug_response/DrugCell/code/predict_drugcell_cpu.py", line 80, in <module>
    predict_data, cell2id_mapping, drug2id_mapping = prepare_predict_data(opt.predict, opt.cell2id, opt.drug2id)
  File "/Users/yoshitakainoue/code/graph_neural_network_drug_response/DrugCell/code/util.py", line 105, in prepare_predict_data
    test_feature, test_label = load_train_data(test_file, cell2id_mapping, drug2id_mapping)
  File "/Users/yoshitakainoue/code/graph_neural_network_drug_response/DrugCell/code/util.py", line 93, in load_train_data
    feature.append([cell2id[tokens[0]], drug2id[tokens[1]]])
KeyError: 'CC1=CC(=O)C=CC1=O'
```

[DrugCell](https://github.com/inoue0426/DrugCell/blob/5df5e6a2b1c9f730ebc24aef227bd215b4a4046e/code/util.py#L85-L96) check the drug index here and rcellminer has not listed drug (SMILES), so this error occurs.

```python

def load_train_data(file_name, cell2id, drug2id):
	feature = []
	label = []


	with open(file_name, 'r') as fi:
		for line in fi:
			tokens = line.strip().split('\t')


			feature.append([cell2id[tokens[0]], drug2id[tokens[1]]])
			label.append([float(tokens[2])])


	return feature, label
```

### rcellminer 

|   | Cell Line            | SMILES                                                         |
| - | ------------ | --------------------------------------------------------- |
| 0 | 786O\_KIDNEY | B.C(CN1CC1)O\[SI\](C2CCCCC2)(C3CCCCC3)C4CCCCC4            |
| 1 | 786O\_KIDNEY | B.CS(=O)(=O)O\[C@H\]1CN2C\[C@@H\](O)\[C@@H\](O)\[C@H\]... |
| 2 | 786O\_KIDNEY | BC(=O)NC(CC(C)C)C(=O)NCC(=O)NC1C(O)C(=O)C2SCCC12          |
| 3 | 786O\_KIDNEY | BRC(BR)(BR)\[HG\]C1CCCCC1                                 |
| 4 | 786O\_KIDNEY | BRC(BR)C(=O)C(BR)C(BR)C1CCCCC1                            |

### DrugCell's training data 

|   | Cell Line    | SMILES                                                |
| - | ------------ | ----------------------------------------------------- |
| 0 | 786O\_KIDNEY | B(\[C@H\](CC(C)C)NC(=O)\[C@H\](CC1=CC=CC=C1)NC(=O)... |
| 1 | 786O\_KIDNEY | C1=CC(=CC=C1CCC(=O)C2=C(C=C(C=C2O)O)O)O               |
| 2 | 786O\_KIDNEY | C1=CC=C(C=C1)COC2=CC3=C(C=C2)NC(=C3)C(=O)O            |
| 3 | 786O\_KIDNEY | CC(C)N1C(=O)/C(=C\\C2=CC=C(O2)SC3=NC4=CC=CC=C4N...    |
| 4 | 786O\_KIDNEY | CC1=\[N+\](C2=C(N1CCOC)C(=O)C3=CC=CC=C3C2=O)CC4=...   |

The DrugCell model requires the same Cell Line name and SMILES for the test data.
So, we need to create the pretrained model from rcellminer dataset.

**Comment by inoue0426** [comment]
[branch](https://github.com/cannin/graph_neural_network_drug_response/tree/6-drugcell-test/DrugCell)

Finally, I can get results.
For the preprocess to run the DrugCell, this is the procedure.

1. get the PubChem ID and NSC number.
2. get the Cell Line, NSC number, and score. [~notebook](https://github.com/cannin/graph_neural_network_drug_response/blob/6-drugcell-test/notebook/1.%20Data%20Extraction%20%5BR%5D%20.ipynb)
3. From the PubChem ID, get the SMILES.
4. From the 1. and 3. files, create Cell Line, SMILES, score table. [~notebook](https://github.com/cannin/graph_neural_network_drug_response/blob/6-drugcell-test/notebook/2.%20Preprocess%20%5BPython%5D.ipynb)
5. Use it for test data. [notebook](https://github.com/cannin/graph_neural_network_drug_response/blob/6-drugcell-test/notebook/3.%20DrugCell%20Sample%20%5BPython%5D.ipynb)

By this pipeline, I was able to show that we can use rcellminer data to run the DrugCell #6

**Comment by inoue0426** [comment]
I added the preprocess for test data to match the distribution of train data.  [notebook](https://github.com/cannin/graph_neural_network_drug_response/blob/6-drugcell-test/notebook/2.%20Preprocess%20%5BPython%5D.ipynb)
Specifically, I selected only the data that fall within the Score range of the Training Data.  
This brings the Correlation to 0.25. [notebook](https://github.com/cannin/graph_neural_network_drug_response/blob/6-drugcell-test/notebook/3.%20DrugCell%20Sample%20%5BPython%5D.ipynb)
